### ISSUE TITLE
Deleting match does not delete Goals

### ISSUE THREAD

**Issue by jaynewey** [jameschamberlain/Football-Team-Tracker#10] opened 2020-10-08 18:15 UTC
Hi, nice app!

When I delete a match with assigned goalscorers, I've noticed that the goal count in the `Stats` tab remains unchanged. It seems that it still counts the goals from deleted matches. I've tried this more than once to ensure it wasn't a one-off.

Is this intended behaviour?

Regards

**Comment by jameschamberlain** [comment] 2020-10-08 20:19
Hey, thanks for pointing this out, I hadn't picked it up in my internal testing. This isn't intended behaviour. The stats tab should update. It is now fixed in commit f9aabdf. I'll publish this to the Play Store the next chance I get.

**Closed as completed by jameschamberlain** 2020-10-08 20:19 UTC
Labels: bug
